services:
  backend:
    image: sibacode/bcnnpotato
    container_name: backend
    ports:
      - "8001:8001"
    networks:
      - app-network

  frontend:
    image: sibacode/fcnnpotato
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - app-network
    environment:
      - REACT_APP_BACKEND_URL=http://backend:8001

networks:
  app-network:
    driver: bridge
